/*
 * Jakefile
 * TracerTest
 *
 * Created by You on October 18, 2010.
 * Copyright 2010, Your Company All rights reserved.
 */

var ENV = require("system").env,
    FILE = require("file"),
    JAKE = require("jake"),
    task = JAKE.task,
    FileList = JAKE.FileList,
    app = require("cappuccino/jake").app,
    configuration = ENV["CONFIG"] || ENV["CONFIGURATION"] || ENV["c"] || "Debug",
    OS = require("os");

app ("TracerTest", function(task)
{
    task.setBuildIntermediatesPath(FILE.join("Build", "TracerTest.build", configuration));
    task.setBuildPath(FILE.join("Build", configuration));

    task.setProductName("TracerTest");
    task.setIdentifier("com.cacaodev.TracerTest");
    task.setVersion("1.0");
    task.setAuthor("cacaodev");
    task.setEmail("cacaodev@gmail.com");
    task.setSummary("TracerTest");
    task.setSources((new FileList("**/*.j")).exclude(FILE.join("Build", "**")));
    task.setResources(new FileList("Resources/**"));
    task.setIndexFilePath("index.html");
    task.setInfoPlistPath("Info.plist");

    if (configuration === "Debug")
        task.setCompilerFlags("-DDEBUG -g");
    else
        task.setCompilerFlags("-O");
});

task ("default", ["TracerTest"], function()
{
    printResults(configuration);
});

task ("build", ["default"]);

task ("debug", function()
{
    ENV["CONFIGURATION"] = "Debug";
    JAKE.subjake(["."], "build", ENV);
});

task ("release", function()
{
    ENV["CONFIGURATION"] = "Release";
    JAKE.subjake(["."], "build", ENV);
});

task ("run", ["debug"], function()
{
    OS.system(["open", FILE.join("Build", "Debug", "TracerTest", "index.html")]);
});

task ("run-release", ["release"], function()
{
    OS.system(["open", FILE.join("Build", "Release", "TracerTest", "index.html")]);
});

task ("deploy", ["release"], function()
{
    FILE.mkdirs(FILE.join("Build", "Deployment", "TracerTest"));
    OS.system(["press", "-f", FILE.join("Build", "Release", "TracerTest"), FILE.join("Build", "Deployment", "TracerTest")]);
    printResults("Deployment")
});

task ("desktop", ["release"], function()
{
    FILE.mkdirs(FILE.join("Build", "Desktop", "TracerTest"));
    require("cappuccino/nativehost").buildNativeHost(FILE.join("Build", "Release", "TracerTest"), FILE.join("Build", "Desktop", "TracerTest", "TracerTest.app"));
    printResults("Desktop")
});

task ("run-desktop", ["desktop"], function()
{
    OS.system([FILE.join("Build", "Desktop", "TracerTest", "TracerTest.app", "Contents", "MacOS", "NativeHost"), "-i"]);
});

function printResults(configuration)
{
    print("----------------------------");
    print(configuration+" app built at path: "+FILE.join("Build", configuration, "TracerTest"));
    print("----------------------------");
}
